### PR TITLE
check role assignment for tf state store

### PR DESCRIPTION
**Pull request by sebader**

### CODE REVIEW

**Comment by sebader** [comment]
and here https://github.com/Azure/AlwaysOn-Foundational-Connected/pull/62

**Comment by msimecek** [comment]
Looking at the e2e run here: https://dev.azure.com/AlwaysOn/Foundational-Online/_build/results?buildId=355&view=logs&j=5fdb0d15-1437-5062-16ec-e29b9e540e5a&t=4d0756f3-74ed-507a-95c8-475bc88721f9 I don't see  log messages for the role assignment...

**Comment by sebader** [comment]
yeah I added the else-logging after the test run. do you want to see it? :)

**Comment by sebader** [comment]
you in fact revealed that logging the SP id does not make sense as it gets redacted :) changed that
image

**Review by msimecek — APPROVED** [review]
Cool, thanks :)

**Pull request merged**
