### PR TITLE
Component updates

### PR DESCRIPTION
**Pull request by msimecek**
Collecting and testing bunch of dependa updates from today.

### CODE REVIEW

**Comment by msimecek** [comment]
https://dev.azure.com/AlwaysOn/Foundational-Online/_build/results?buildId=401&view=results

**Comment by sebader** [comment]
before merging, should we fix the deprecation warning in AKS terraform? @heoelri

**Comment by msimecek** [comment]
Since it's not a component update I suggest we create a separate work item for it.

**Comment by heoelri** [comment]
> Since it's not a component update I suggest we create a separate work item for it.

I need a bit - it's already in e2e for validation.

**Review by heoelri — APPROVED** [review]

**Pull request merged**
