### PR TITLE
lock state store

### PR DESCRIPTION
**Pull request by heoelri**

### CODE REVIEW

**Comment by heoelri** [comment]
This is only applied at storage account / resource group creation time - this does not make too much sense. Will change it to set the locks at every execution.

**Comment by heoelri** [comment]
Testing it here: https://dev.azure.com/AlwaysOn/Foundational-Online/_build/results?buildId=402&view=logs&s=324f4ed7-bdf4-5a39-9186-37c4a0e7ec24&j=9a62b2c6-931b-5ee5-4062-7dadbfc43efc

**Comment by sebader** [comment]
why do we also need a lock at the RG? you wont be able to delete the RG anyway if there is a resource in there with a lock, will you?

**Comment by heoelri** [comment]
True, its a bit redundant. Will drop the resource group.

**Comment by heoelri** [comment]
image

Looks good.

**Comment by heoelri** [comment]
Sure thing.

**Pull request merged**
